version: "3.8"

services:

  redis:
    image: redis:7-alpine
    container_name: codearena-redis

    ports:
      - "6379:6379"

    networks:
      - codearena-network


  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: codearena-server

    ports:
      - "5000:5000"

    env_file:
      - ./server/.env

    depends_on:
      - redis

    networks:
      - codearena-network


  executor:

    build:
      context: ./executor
      dockerfile: Dockerfile

    container_name: codearena-executor

    depends_on:
      - redis

    networks:
      - codearena-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:

  codearena-network:
    driver: bridge